### ISSUE TITLE
Can not parse special date assign statement

### ISSUE THREAD

**Issue by ScofieldXu** [raverkamp/plsql-code-coverage#1]
A date assign statement like "TmpDate := Date '1970-1-1' + 100000 + INTERVAL '8' HOUR;" will raise an exception as "can not parse: expecting semi colon at xx/xx".
Oracle database version is 11.2.0.3.0

**Comment by raverkamp** [comment]
Fixed with your patch. Thank you.
Most likely I will fix this also in the separate PL/SQL parser project and then do a copy from there.
But for now this is fine.
Who uses intervals? I just usually add 1/24 for a hour anyway. :-)
