### ISSUE TITLE
Tool not taking the functions and procedures created outside of package.

### ISSUE THREAD

**Issue by sinsharat** [raverkamp/plsql-code-coverage#12]
pre-requisite:-
1) DB contains the packages which in-turn contains functions.
2) DB contains some functions/procedure out side of packages also.

'steps to reproduce:-
1) connect to DB with thin
2) click yes to recreate DB objects needed to run code coverage.

Actual result:-
1) Out of 4 package only for 2 code coverage object is created and showed in left pannel.
2) functions/procedures present outside package are not listed in left pannel. Also code coverage objects for same is not created.

Expected Result:- 
1) all packges must be shown in left pannel.
2) All functions/procedures outside the package must be listed in left panel.

**Comment by raverkamp** [comment]
Currently there is no support for code coverage on stand alone procedures/functions.
So how many procedures/functions do you have? And how many packages are shown in the left panel.
Are packages missing in the left panel?

**Comment by raverkamp** [comment]
There are now answers. So I close this issue.
