### ISSUE TITLE
runtime exception

### ISSUE THREAD

**Issue by vaibhav1622** [raverkamp/plsql-code-coverage#13]
while instrumenting the package getting 2 error.

1) RunTime exception with message "start should be smaller than end".

2) syntax error "expecting ;" at the place where cursor is used with dynamic query.

**Comment by raverkamp** [comment]
Without any PL/SQL code sample (small!) on which the system fails, I can not do anything.
Can you supply a standalone sample where code coverage fails?

**Comment by raverkamp** [comment]
There are now answers. So I close this issue.
