### ISSUE TITLE
Can not parse statement include float number

### ISSUE THREAD

**Issue by ScofieldXu** [raverkamp/plsql-code-coverage#3]
A statement like "v_num:= 1234 + (to_number(v_val) - 1.4) / 0.1;" will raise an exception as "can not parse: expecting expression at xx/xx".
Oracle database version is 11.2.0.3.0

**Comment by raverkamp** [comment]
Fixed with your patch. Thank you.
Most likely I will fix this also in the separate PL/SQL parser project and then do a copy from there.
But for now this is fine.
Who uses intervals? I just usually add 1/24 for a hour anyway. :-)
