### ISSUE TITLE
log in front of statement makes SQL%[ROWCOUNT|FOUND|NOTFOUND] get wrong result

### ISSUE THREAD

**Issue by ScofieldXu** [raverkamp/plsql-code-coverage#5]
sql cursor didn't allowed commit or rollback between last statement (insert\update\delete) and itself,but in log procedure,we do another statement and commit at last,it will cause wrong result.
for example:
update a set c = 'c' where d  'd';
if sql%rowcount <> 1 then
...
after instrument,the code become
"$log"(2);update a set c = 'c' where d  = 'd';
"$log"(3);if sql%rowcount <> 1 then
...
it make if statement didn't get what it wants.
so, I want to instrument the log code at the end of SQL%XXX statement.

**Comment by raverkamp** [comment]
Fixed for "reasonable" code. E.g. unreasonable: the dml statement and the corresponding reference to sql%rowcount are not in the same scope.
