### ISSUE TITLE
storage line number into database

### ISSUE THREAD

**Issue by ScofieldXu** [raverkamp/plsql-code-coverage#7]
storage line number into aaa_coverage_statements table

**Comment by raverkamp** [comment]
Hi,
I was just going to ask why do we need the line number.
But then I checked the source and noticed that it is still in the table script.
So I have to ask myself why it is still there.
And why are the TXT_START and TXT_END columns still there.
At least these two columns are not needed, we have the source.

Do you need the line_number column?

Another point are the changes to the parser. For the sql%rowcount problem
I made Exppression a subclass of Ranged. Having the line information 
on the in the Range is useful.

Usually I make changes in my Github parser project and copy them
to code coverage project. Maybe someday I will use it for other things.
Not a great workflow, but for one person it is OK.

I think I have to look at Git modules to include this project directly
into code coverage. And then you can add your patches.

So I will close this issue and look into git sub modules.

Kind Regards,
Roland
